# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SpecAlertTool' do

pod 'Masonry', '~> 0.6.4'

end

target 'SpecAlertToolTests' do

end

target 'SpecAlertToolUITests' do

end

